no_std support
scriptjunkie/codec2 pull request #2
Opened 2023-11-19 11:09 UTC by CBJamo

This is a draft to add no_std support. I simply added the `#[no_std]` directive and fixed compiler errors, swapped all floats to f32, and added micromath to provide float operations. The tests still pass, and the example encode/decode program works the same. I have not tested against the original codec2 implementation, though I would be quite surprised if it didn't work.

2023-11-20 04:33 UTC, scriptjunkie commented
This seems good, move out of draft when you're ready.

2023-11-20 05:46 UTC, CBJamo commented
I did a little additional testing, using the C reference, this no_std, and the existing implementation to check if there are differences in the outputs. Here are all the versions in an [audacity project](http://cbjamo.com/codec2-rs-testing.aup3).

I don't know audacity well enough to do anything but compare them visually, but to my eye the the no_std encode must produce similar output to the reference and existing impls, but the no_std decode introduces more noise. I can't tell the difference by ear, however. 

In my mind that's an acceptable outcome, but if you want exactly the same performance I'll dig deeper. I suspect the micromath approximations only effect decoding and that switching to a slower but more accurate approach would fix the perf difference.

2024-02-20 02:40 UTC, CBJamo commented
I feel like more testing should be done, but moving micromath/no_std behind a feature feels like an ok middle road. FYI, I'm going to look into getting rid of alloc as well, though I think that will be difficult.

2025-07-04 16:54 UTC, Ralith commented
@scriptjunkie friendly ping? This would be nice to have!

2025-07-04 16:58 UTC, Ralith requested changes

2025-07-04 16:58 UTC, Ralith commented on Cargo.toml
> +micromath = "2.1.0"
This should be marked optional.

2025-07-04 16:58 UTC, Ralith commented on src/lib.rs
> +#![cfg_attr(micromath, no_std)]
Here and below, you want `feature = "micromath"`, not just `micromath`. As-is this is always disabled.

2025-07-05 20:51 UTC, CBJamo commented
Thanks for the review and good catches Ralith, all fixed.

2025-07-15 13:48 UTC, merged

2025-07-15 13:48 UTC, scriptjunkie commented
Pardon the long delay!